{
	'name': 'DINCEL MANUFACTURE ',
	'version':'1.0',
	'description':"""
		DINCEL MANUFACTURE Module
		""",
	'author':'Shukra Rai',
	'website':'www.dincel.com.au',
	'depends':['base','base_setup','sale', 'crm','mrp','dincelproduct'],
	'data':['dincelmanufacture.xml',
			'dincelmrp.xml',
			'dincelmrp_purchase.xml',
			'dincelmanufacture_menu.xml',
			'dincelmrp_saleorder.xml',
			'dincelmrp_so_schedule.xml',
			'dincelmrp_route.xml',
			'dincelmrp_accessories.xml',
			'dincelmrp_report.xml',
			'dincelmrp_log_report.xml',
			'wizard/schedule_mrp.xml',
			'views/report_mo_pqreport.xml',
			'views/report_mrp_logs.xml',
			'wizard/mrp_produce.xml',
			'wizard/schedule_delivery.xml',
			'wizard/mrp_produce_new.xml',
			'wizard/schedule_mrp_tmp.xml',
			'wizard/schedule_mrp_print.xml',
			'wizard/mrp_stock_produce.xml',
			],
	'init_xml': [],
	'js': [],
	'css': [],
	'qweb': [], 
	'demo':[],
	'installable':True,
	'auto_install':False,
}


