{
	'name': 'DINCEL ACCOUNT ',
	'version':'1.0',
	'description':"""
		DINCEL ACCOUNT Custom Module
		""",
	'author':'Shukra Rai',
	'website':'www.dincel.com.au',
	'depends':['base','base_setup','web','account','sale','dincelstock'],
	'data':[
		'dincelaccount.xml',
		'dincelaccount_menu.xml',
		'dincelaccount_external.xml',
		'dincelaccount_tax.xml',
		'dincelaccountsettings.xml',
		'dincelaccount_inventory.xml',
		'res_config_xml.xml',
		'dincelaccount_invoice_view.xml',
		'dincelaccount_supplier.xml',
		'dincelaccount_sale.xml',
		'dincelaccount_purchase.xml',
		'dincelaccount_partner.xml',
		'dincelproductsettings.xml',
		'dincelaccount_sale_order.xml',
		'dincelaccount_voucher.xml',
		'dincelaccount_mail.xml',
		'views/report_financial2.xml',
		'views/report_trialbalance1.xml',
		'views/report_generalledger1.xml',
		'views/report_general_ledger_dcs.xml',
		'report/dcs_account_report.xml',
		'views/report_gledger2.xml',
		'views/report_tax_dcs.xml',
		'views/report_tax_dcs_new.xml',
		'views/report_partner_statement.xml',
		'views/report_partner_invoice.xml',
		'views/report_partner_aging.xml',
		'views/report_account_reconcile.xml',
		'views/report_supplier_payment.xml',
		'wizard/purchase_invoice_pay.xml',
		'wizard/purchase_nonstock_pay.xml',
		'edi/sale_order_action_data.xml',
		'wizard/sale_order_revise.xml',
		'wizard/sale_order_balance_inv.xml',
		'wizard/download_aba.xml',
		'wizard/invoice_payreverse.xml',
		'wizard/dincelaccount_invoice_multi.xml',
		'wizard/saleorder_approve.xml',
		'dincelaccount_order_approve.xml',
		],
	'init_xml': [],
	'js': [],
	'css': [],
	'qweb': [], 
	'demo':[],
	'installable':True,
	'auto_install':False,
}


